---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: locale-fedora-latest
    image: fedora:latest
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        locale_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: fedora-latest
